name: branch_deploy

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read

jobs:
  branch-deploy:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    outputs:
      continue: ${{ steps.branch-deploy.outputs.continue }}
      ref: ${{ steps.branch-deploy.outputs.ref }}
    steps:
      - uses: github/branch-deploy@v7.3.0
        id: branch-deploy

  deploy:
    needs: branch-build
    if: ${{ jobs.branch-deploy.outputs.continue == 'true' }}
    uses: ./.github/workflows/build_and_deploy.yml
    secrets: inherit
    with:
      ref: ${{ jobs.branch-deploy.outputs.ref }}
