name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run"
        type: environment
        default: production
        required: true

jobs:
  deploy:
    environment:
      name: ${{ github.event.inputs.environment }}
    uses: ./.github/workflows/build_and_deploy.yml
