name: deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "deploy branch"
        required: true
        default: "master"
        type: choice
        options:
          - master
          - release
          - develop

jobs:
  deploy:
    uses: ./.github/workflows/build_and_deploy.yml
    secrets: inherit
    with:
      ref: ${{ inputs.branch }}
