name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run"
        type: environment
        default: production
        required: true

jobs:
  deploy:
    uses: ./.github/workflows/build_and_deploy.yml
