name: release
on: [ workflow_dispatch ]
jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: create-release-pr
        uses: grassedge/git-pr-release-action@v1.0
        with:
          base: release
          head: master
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: release
          assign: true
